package:
  name: esspolarization

  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..


{% set pyproject = load_file_data('pyproject.toml') %}
{% set dependencies = pyproject.get('project', {}).get('dependencies', {}) %}


requirements:
  build:
    - setuptools
    - setuptools_scm
  run:
    - dask
    - python>=3.10
    - python-graphviz
    - sciline>=23.12.0
    - scipp>=23.8.0
    - scippnexus>=23.11.0

  {% for package in dependencies %}
    - {% if package == "graphviz" %}python-graphviz{% else %}{{ package }}{% endif %}
  {% endfor %}


test:
  imports:
    - ess.polarization
  requires:
    - pytest
  source_files:
    - pyproject.toml
    - tests/
  commands:
    # We ignore warnings during release package builds
    - python -m pytest -Wignore tests

build:
  noarch: python
  script:
    - python -m pip install .

about:
  home: https://github.com/scipp/esspolarization
  license: BSD-3-Clause
  summary: Polarization data reduction for the European Spallation Source
  description: Polarization data reduction for the European Spallation Source
  dev_url: https://github.com/scipp/esspolarization
  doc_url: https://scipp.github.io/esspolarization
